---
# Tasks file for initial setup

- name: Enable non-free and non-free-firmware repositories
  deb822_repository:
    name: debian
    types: deb
    uris: http://deb.debian.org/debian
    suites: '{{ ansible_distribution_release }}'
    components:
      - main
      - contrib
      - non-free

- name: Install base packages
  tags: packages,base
  ansible.builtin.apt:
    name:
      - sudo
      - curl
      - htop
      - iftop
      - iotop
      - vim
      - openssh-server
      - rsync
      - unattended-upgrades
      - aptitude
      - apt-file
      - tmux
      - lnav
      - parted
      - fastfetch
      - tree
      - tcpdump
    force_apt_get: true

- name: Copy bash aliases to skel
  tags: base,config
  ansible.builtin.copy:
    src: bash_aliases
    dest: /etc/skel/.bash_aliases
    owner: root
    group: root
    mode: "0644"

- name: Copy bash aliases to user home
  tags: base,config
  ansible.builtin.copy:
    src: bash_aliases
    dest: /home/phil/.bash_aliases
    owner: phil
    group: phil
    mode: "0644"

